// flow-typed signature: 3c2f7ef6c6da475bb5d3ef77e50433b0
// flow-typed version: <<STUB>>/touch_v3.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'touch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'touch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'touch/bin/nodetouch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'touch/bin/nodetouch.js' {
  declare module.exports: $Exports<'touch/bin/nodetouch'>;
}
declare module 'touch/index' {
  declare module.exports: $Exports<'touch'>;
}
declare module 'touch/index.js' {
  declare module.exports: $Exports<'touch'>;
}
